language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

git:
  depth: 1

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7
      env:
        - COMPOSER_FLAGS="--prefer-stable"
    - php: 7.1

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source --ignore-platform-reqs

script:
  - vendor/bin/phpunit --report-useless-tests

after_script:
  - bash -c '[[ -f "build/logs/clover.xml" ]] && wget https://scrutinizer-ci.com/ocular.phar'
  - bash -c '[[ -f "build/logs/clover.xml" ]] && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml'
